version: "3.9"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "file:/data/dev.db"
    volumes:
      - dbdata:/data
    command: >-
      sh -c "npx prisma migrate deploy && (node prisma/seed.js || true) && npm run start"
    restart: unless-stopped

volumes:
  dbdata:
