services:
  web:
    build: .
    ports:
      - "3000:3000"            # change to "3001:3000" if 3000 is busy
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - DATABASE_URL=file:/data/dev.db
    volumes:
      - dbdata:/data
    command: >
      sh -c "npx prisma migrate deploy;
             node prisma/seed.js || true;
             npm run start"
volumes:
  dbdata:
